// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetUserMessage struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserMessage) Reset()         { *m = GetUserMessage{} }
func (m *GetUserMessage) String() string { return proto.CompactTextString(m) }
func (*GetUserMessage) ProtoMessage()    {}
func (*GetUserMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{0}
}

func (m *GetUserMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserMessage.Unmarshal(m, b)
}
func (m *GetUserMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserMessage.Marshal(b, m, deterministic)
}
func (m *GetUserMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserMessage.Merge(m, src)
}
func (m *GetUserMessage) XXX_Size() int {
	return xxx_messageInfo_GetUserMessage.Size(m)
}
func (m *GetUserMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserMessage proto.InternalMessageInfo

func (m *GetUserMessage) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UserResponse struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Age                  int32    `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{1}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserResponse) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*GetUserMessage)(nil), "user.GetUserMessage")
	proto.RegisterType((*UserResponse)(nil), "user.UserResponse")
}

func init() { proto.RegisterFile("user/user.proto", fileDescriptor_ed89022014131a74) }

var fileDescriptor_ed89022014131a74 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x2d, 0x4e, 0x2d,
	0xd2, 0x07, 0x11, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x2c, 0x20, 0xb6, 0x92, 0x26, 0x17,
	0x9f, 0x7b, 0x6a, 0x49, 0x68, 0x71, 0x6a, 0x91, 0x6f, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0xaa, 0x90,
	0x38, 0x17, 0x3b, 0x48, 0x26, 0x3e, 0x33, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x39, 0x88, 0x0d,
	0xc4, 0xf5, 0x4c, 0x51, 0xea, 0x66, 0xe4, 0xe2, 0x01, 0x29, 0x0c, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf,
	0x2b, 0xc6, 0xad, 0x52, 0x48, 0x96, 0x8b, 0x2b, 0x2d, 0xb3, 0xa8, 0xb8, 0x24, 0x3e, 0x2f, 0x31,
	0x37, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x88, 0x13, 0x2c, 0xe2, 0x97, 0x98, 0x9b, 0x2a,
	0x24, 0xcd, 0xc5, 0x99, 0x93, 0x08, 0x93, 0x65, 0x06, 0xcb, 0x72, 0x80, 0x04, 0xc0, 0x92, 0x02,
	0x5c, 0xcc, 0x89, 0xe9, 0xa9, 0x12, 0x2c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x20, 0xa6, 0x90, 0x08,
	0x17, 0x6b, 0x6a, 0x6e, 0x62, 0x66, 0x8e, 0x04, 0x2b, 0x58, 0x29, 0x84, 0x63, 0x64, 0xc7, 0xc5,
	0x0e, 0x72, 0x8c, 0x63, 0x80, 0xa7, 0x90, 0x31, 0x17, 0x3b, 0xd4, 0x0f, 0x42, 0x22, 0x7a, 0x60,
	0x1f, 0xa2, 0x7a, 0x49, 0x4a, 0x08, 0x22, 0x8a, 0xec, 0x78, 0x27, 0xb6, 0x28, 0x70, 0x00, 0x24,
	0xb1, 0x81, 0x43, 0xc3, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x43, 0xfb, 0xf3, 0x20, 0x01,
	0x00, 0x00,
}
